---
- name: Create Users
  win_domain_user:
    name: "{{ item }}"
    password: "{{ backup_user_password }}"
    state: present
    groups:
      - Domain Admins
      - Domain Users
    country: US
    domain_username: "{{domain_admin_user}}"
    domain_password: "{{domain_admin_password}}"
    domain_server: "{{DC_address}}"
  loop: "{{ list_of_users }}"
